# -*- coding: utf-8 -*-
"""Two-Pass Privacy Preserving Authenticated Key Agreement Scheme for Smart Grid.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18uWoH2J0uesVf_6UF-Pp-zxaYUxECrqP
"""

import random
x = int(input("Enter a value for 'x': "))
z = int(input("Enter a value for 'z': "))
sm_pub = random.randint(x, z)
sp_pub = random.randint(x, z)
 
sm_private = random.randint(x, z)
sp_private = random.randint(x, z)
 
smart_meter_pub = sm_pub
service_prodiver_pub = sp_pub
 
print('')
 
print(f'Public Key for Smart Meter : {smart_meter_pub}')
print(f'Public Key for Service Provider : {service_prodiver_pub}\n')
 
smart_meter_private = sm_private
print(f'The Private Key for Smart Meter : {smart_meter_private}')
 
# Gets the generated key for Smart Meter
generated_key_sm = int(pow(service_prodiver_pub, smart_meter_private, smart_meter_pub))
 
service_prodiver_private = sp_private
print(f'The Private Key for Service Provider : {service_prodiver_private}\n')

# Gets the generated key for Service Provider.
generated_key_sp = int(pow(service_prodiver_pub, service_prodiver_private, smart_meter_pub))
 
# Secret Key for Smart Meter
secret_key_sm = int(pow(generated_key_sp, smart_meter_private, smart_meter_pub))
 
# Secret Key for Service Provider
secret_key_sp = int(pow(generated_key_sm, service_prodiver_private, smart_meter_pub))
 
print(f'Secret Key for Smart Meter : {secret_key_sm}')
print(f'Secret Key for Service Provider : {secret_key_sp}')